//DEER_0(id, name, word, fontcolor, color, fillcolor, shape, style, code)
//DEER_1(id, name, word, fontcolor, color, fillcolor, shape, style, code)
//DEER_2(id, name, word, fontcolor, color, fillcolor, shape, style, code)

#define TO_STRING(prefix) { prefix + std::to_string (value.value) }

DEER_0 ( 0,        Digit, TO_STRING      (""), "darkgreen", "darkgreen",   "#98FF66",     "box", "rounded, filled", { give_Digit    (current, write); })
DEER_0 ( 1,         Name, TO_STRING ("name_"), "darkgreen", "darkgreen",   "#98FF66",     "box", "rounded, filled", { give_Name     (current, write); })
DEER_1 ( 2,        Block,             "block",     "black",     "black", "lightgrey", "ellipse", "rounded, filled", { give_Block    (current, write); })
DEER_1 ( 3,      DeclVar,          "decl_var",     "black",     "black", "lightgrey", "ellipse", "rounded, filled", { give_DeclVar  (current, write); })
DEER_1 ( 4,     DeclFunc,         "decl_func",     "black",     "black", "lightgrey", "ellipse", "rounded, filled", { give_DeclFunc (current, write); })
DEER_1 ( 5,         Call,              "call",     "black",     "black", "lightgrey", "ellipse", "rounded, filled", { give_Call     (current, write); })
DEER_1 ( 6,       Params,            "params",     "black",     "black", "lightgrey", "ellipse", "rounded, filled", {})
DEER_1 ( 7,        Equal,                "==",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Equal_NotEqual_Less_LessEqual_More_MoreEqual (current, write, "je", "jne"); })
DEER_1 ( 8,     NotEqual,                "!=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Equal_NotEqual_Less_LessEqual_More_MoreEqual (current, write, "jne", "jn"); })
DEER_1 ( 9,          And,                "&&",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_And (current, write); })
DEER_1 (10,           Or,                "||",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Or  (current, write); })
DEER_1 (11,          Not,                 "!",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (12,    LessEqual,                "<=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Equal_NotEqual_Less_LessEqual_More_MoreEqual (current, write, "je", "jne"); })
DEER_1 (13,    MoreEqual,                ">=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Equal_NotEqual_Less_LessEqual_More_MoreEqual (current, write, "je", "jne"); })
DEER_1 (14,          Mul,                 "*",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Add_Sub_Mul_Div_Mod (current, write, "mul"); })
DEER_1 (15,          Div,                 "/",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Add_Sub_Mul_Div_Mod (current, write, "div"); })
DEER_1 (16,          Mod,                "%%",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Add_Sub_Mul_Div_Mod (current, write, "mod"); })
DEER_1 (17,          Add,                 "+",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Add_Sub_Mul_Div_Mod (current, write, "add"); })
DEER_1 (18,          Sub,                 "-",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Add_Sub_Mul_Div_Mod (current, write, "sub"); })
DEER_1 (19,   Assingment,                 "=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", { give_Assignment (current, write); })
DEER_1 (20,         Less,                 "<",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (21,         More,                 ">",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (22,       BitAnd,                 "&",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (23,        BitOr,                 "|",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (24,       BitXor,                 "^",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (25,       BitNot,                 "~",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (26,    ShiftLeft,                "<<",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (27,   ShiftRight,                ">>",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (28,     AddEqual,                "+=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (29,     SubEqual,                "-=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (30,     MulEqual,                "*=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (31,     DivEqual,                "/=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (32,     ModEqual,                "%=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (33,     AndEqual,                "&=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (34,      OrEqual,                "|=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (35,     XorEqual,                "^=",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (36,    Increment,                "++",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (37,    Decrement,                "--",       "red",       "red",   "#FFCCC9",     "box", "rounded, filled", {})
DEER_1 (38,           If,                "if",      "blue",      "blue", "lightblue",     "box", "rounded, filled", { give_If (current, write); })
DEER_1 (39,        While,             "while",      "blue",      "blue", "lightblue",     "box", "rounded, filled", { give_While (current, write); })
DEER_1 (40,          Int,               "int",      "blue",      "blue", "lightblue",     "box", "rounded, filled", {})
DEER_1 (41,         Void,              "void",      "blue",      "blue", "lightblue",     "box", "rounded, filled", {})
DEER_1 (42,       Return,            "return",      "blue",      "blue", "lightblue",     "box", "rounded, filled", { give_Return (current, write); })
DEER_1 (43,        Break,             "break",      "blue",      "blue", "lightblue",     "box", "rounded, filled", {})
DEER_1 (44,          Out,               "out",      "blue",      "blue", "lightblue",     "box", "rounded, filled", { give_Out (current, write); })
DEER_1 (45,     Continue,          "continue",      "blue",      "blue", "lightblue",     "box", "rounded, filled", {})
DEER_1 (46,        Begin,                 "{",     "white",     "white",     "white",     "box", "rounded, filled", {})
DEER_1 (47,          End,                 "}",     "white",     "white",     "white",     "box", "rounded, filled", {})
DEER_1 (48,   EndOfToken,                 ";",     "white",     "white",     "white",     "box", "rounded, filled", {})
DEER_1 (49,  OpenBracket,                 "(",     "white",     "white",     "white",     "box", "rounded, filled", {})
DEER_1 (50, CloseBracket,                 ")",     "white",     "white",     "white",     "box", "rounded, filled", {})
DEER_1 (51,         Else,              "else",     "white",     "white",     "white",     "box", "rounded, filled", {})
DEER_1 (52,        Comma,                 ",",     "white",     "white",     "white",     "box", "rounded, filled", {})
DEER_2 (53,      Include,           "include",    "purple",    "purple",    "purple",     "box", "rounded, filled", {})
DEER_2 (54,       Define,            "define",    "purple",    "purple",    "purple",     "box", "rounded, filled", {})
DEER_2 (55,        Undef,             "undef",    "purple",    "purple",    "purple",     "box", "rounded, filled", {})

#undef TO_STRING
