//DEER(id, name, word, dot_color)
//DEER_DEFAULT(id, name, word, dot_color)

DEER         ( 0,        Digit,                   { Itoa (m.value); }, SetColor ("darkgreen", "darkgreen",   "#98FF66");)
DEER         ( 1,          Var,           { Itoa (m.value, "var_"); }, SetColor ("darkgreen", "darkgreen",   "#98FF66");)
DEER         ( 2,        Block,                               "block", SetColor (     "grey",      "grey", "lightgrey");)
DEER_DEFAULT ( 3,      DeclVar,                            "decl_var", SetColor (     "grey",      "grey", "lightgrey");)
DEER_DEFAULT ( 4,     DeclFunc,                           "decl_func", SetColor (     "grey",      "grey", "lightgrey");)
DEER_DEFAULT ( 5,        Equal,                                  "==", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT ( 6,     NotEqual,                                  "!=", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT ( 7,          And,                                  "&&", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT ( 8,           Or,                                  "||", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT ( 9,    LessEqual,                                  "<=", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (10,    MoreEqual,                                  ">=", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (11,           If,                                  "if", SetColor (     "blue",      "blue", "lightblue");)
DEER_DEFAULT (12,         Else,                                "else", SetColor (    "white",     "white",     "white");)
DEER_DEFAULT (13,        While,                               "while", SetColor (     "blue",      "blue", "lightblue");)
DEER_DEFAULT (14,          Int,                                 "int", SetColor (     "blue",      "blue", "lightblue");)
DEER_DEFAULT (15,         Void,                                "void", SetColor (     "blue",      "blue", "lightblue");)
DEER_DEFAULT (16,        Comma,                                   ",", SetColor (    "white",     "white",     "white");)
DEER_DEFAULT (17,      Include,                            "#include", SetColor (   "purple",    "purple",    "purple");)
DEER_DEFAULT (18,       Define,                             "#define", SetColor (   "purple",    "purple",    "purple");)
DEER_DEFAULT (19,  OpenBracket,                                   "(", SetColor (    "white",     "white",     "white");)
DEER_DEFAULT (20, CloseBracket,                                   ")", SetColor (    "white",     "white",     "white");)
DEER_DEFAULT (21,          Mul,                                   "*", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (22,          Div,                                   "/", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (23,          Mod,                                 "\\%", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (24,          Add,                                   "+", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (25,          Sub,                                   "-", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (26,   Assingment,                                   "=", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (27,         Less,                                   "<", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (28,         More,                                   ">", SetColor (      "red",       "red",   "#FFCCC9");)
DEER_DEFAULT (29,        Begin,                                   "{", SetColor (    "white",     "white",     "white");)
DEER_DEFAULT (30,          End,                                   "}", SetColor (    "white",     "white",     "white");)
DEER_DEFAULT (31,   EndOfToken,                                   ";", SetColor (    "white",     "white",     "white");)
