//DEER(id, name, read, write)
//DEER_DEFAULT(id, name, word) DEER(id, name, printf (word), fscanf (word))


DEER ( 0,        Digit,         "")
DEER ( 1,          Var,         "")
DEER ( 2,        Equal,       "==")
DEER ( 3,     NotEqual,       "!=")
DEER ( 4,          And,       "&&")
DEER ( 5,           Or,       "||")
DEER ( 6,    LessEqual,       "<=")
DEER ( 7,    MoreEqual,       ">=")
DEER ( 8,           If,       "if")
DEER ( 9,         Else,     "else")
DEER (10,        While,    "while")
DEER (11,          Int,      "int")
DEER (12,         Void,     "void")
DEER (13,  Declaration,         "")
DEER (14,        Comma,        ",")
DEER (15,      Include, "#include")
DEER (16,       Define,  "#define")
DEER (17,         None,         "")
DEER (18,  OpenBracket,        "(")
DEER (19, CloseBracket,        ")")
DEER (20,          Mul,        "*")
DEER (21,          Div,        "/")
DEER (22,          Mod,        "\\%")
DEER (23,          Add,        "+")
DEER (24,          Sub,        "-")
DEER (25,   Assingment,        "=")
DEER (26,         Less,        "<")
DEER (27,         More,        ">")
DEER (28,        Begin,        "{")
DEER (29,          End,        "}")
DEER (30,   EndOfToken,        ";")
